---
title: "CaseStudy2 Additional Code"
author: "Christopher Williams"
date: "2022-12-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MASS)
library(tidyverse)
library(readxl)
library(caret)
library(e1071)
library(class)
library(ggmosaic)
library(ggthemes)
case2_full= read.csv("CaseStudy2-data.csv", stringsAsFactors = T)
```

```{r}
#remove uselese varaibles
full = case2_full %>%
  dplyr::select(!c(ID,EmployeeCount,EmployeeNumber,Over18,StandardHours,
                   YearsInCurrentRole,YearsSinceLastPromotion)) %>%
  mutate(Education = factor(Education,ordered = T),
         EnvironmentSatisfaction = factor(EnvironmentSatisfaction,ordered = T),
         JobInvolvement = factor(JobInvolvement,ordered = T),
         JobSatisfaction = factor(JobSatisfaction,ordered = T),
         JobLevel = factor(JobLevel,ordered = T),
         PerformanceRating = factor(PerformanceRating,ordered = T),
         RelationshipSatisfaction = factor(RelationshipSatisfaction,ordered = T),
         StockOptionLevel = factor(StockOptionLevel,ordered = T),
         TrainingTimesLastYear = factor(TrainingTimesLastYear,ordered = T),
         WorkLifeBalance = factor(WorkLifeBalance,ordered = T))

full_noattr = full %>% dplyr::select(!c(Attrition))
full_attr = full %>% dplyr::select(Attrition)


# set controls for reverse feature elimination(RFE) of naive bayes
#ctrl = rfeControl(functions = nbFuncs,
#                  rerank = T,
#                  method = "cv")

# RFE for naive bayes
#nbreverse = rfe(full_noattr[,1:26],full$Attrition, sizes = 3:30,
#                rfeControl = ctrl)

```
############################## step logreg #######################################
# step log reg no oversample
```{r}
fit_log_full = glm(Attrition~.,data = full, family = binomial(link = "logit"))

step = stepAIC(fit_log_full,direction = "both",trace = 0)
stepbic = stepAIC(fit_log_full,direction = "both", k = log(870), trace = 0)

summary(step)
aicpreds = factor(ifelse(predict(step,full_noattr,type = "response")>.5,"Yes","No"))
bicpreds = factor(ifelse(predict(stepbic,full_noattr,type = "response")>.5,"Yes","No"))
confusionMatrix(bicpreds,full_attr$Attrition)
```

# oversampling
```{r}
attr_over = full %>%
  filter(Attrition=="Yes") %>%
  slice_sample(n=380,replace = T)
attr_over = full %>%
  filter(Attrition=="No") %>%
  bind_rows(attr_over)
```

# step log reg with oversample
```{r}
over_noattr = attr_over %>% dplyr::select(!c(Attrition))
over_attr = attr_over %>% dplyr::select(Attrition)

over_log_full = glm(Attrition~.,data = attr_over, family = binomial(link = "logit"))

stepaic_over = stepAIC(over_log_full,direction = "both", trace = 0)
stepbic_over = stepAIC(over_log_full,direction = "both", k = log(870), trace = 0)

aicpreds_over = factor(ifelse(predict(stepaic_over,full_noattr,type = "response")>.5,"Yes","No"))
bicpreds_over = factor(ifelse(predict(stepbic_over,full_noattr,type = "response")>.5,"Yes","No"))

confusionMatrix(aicpreds_over,full_attr$Attrition)
confusionMatrix(bicpreds_over,full_attr$Attrition)

summary(stepaic_over)
```
```{r}
stepaic_over$cal
stepAIC(glm(formula = Attrition ~ BusinessTravel + Department + DistanceFromHome + 
    EnvironmentSatisfaction + Gender + HourlyRate + JobInvolvement + 
    JobLevel + JobRole + WorkLifeBalance + StockOptionLevel + 
    OverTime + JobSatisfaction + MaritalStatus + NumCompaniesWorked + 
    RelationshipSatisfaction + TotalWorkingYears + TrainingTimesLastYear + 
    YearsAtCompany + YearsWithCurrManager+Age, family = binomial(link = "logit"), 
    data = attr_over),steps = 1)
```




























